CREATE TABLE [dbo].[Tiempo]
(
	[Id] NVARCHAR(50) NOT NULL CONSTRAINT [PK_Tiempo] PRIMARY KEY,
	[Fecha] DATE NOT NULL, 
	[Dia] INT NOT NULL,
	[Semana] INT NOT NULL,
	[Mes] INT NOT NULL,
	[Semestre] INT NOT NULL,
	[Anio] INT NOT NULL
)
